### ISSUE TITLE
ERD,Table schema 작성

### ISSUE THREAD

**Issue by eunchae-jeon** [boostcamp-2020/IssueTracker-23#2]
- [x] ERD 설계
- [x] ERD를 기반으로 Table schema 작성

[Database 설계](https://github.com/boostcamp-2020/IssueTracker-23/wiki/Database)

**Comment by ypd01018** [comment]
댓글 달아봅니다

**Comment by ByeongjaeJeon** [comment]
dkdk
fgdgd
